export const COUNTER_INCRIMENT = 'COUNTER_INCRIMENT'; //Will add one to counter
export const COUNTER_DECRIMENT = 'COUNTER_DECRIMENT'; //Will subscruct one from counter


export const USER_AUTHORIZATION_START = 'USER_AUTHORIZATION_START';
export const USER_AUTHORIZATION_SUCCESS = 'USER_AUTHORIZATION_SUCCESS';
export const USER_AUTHORIZATION_FAIL = 'USER_AUTHORIZATION_FAIL';
export const USER_LOG_OUT = 'USER_LOG_OUT';
export const USER_FILLED_INFO = 'USER_FILLED_INFO';

export const POPUP_UNIVERSAL_SWITCH = 'POPUP_UNIVERSAL_SWITCH';

export const SET_AIRTABLE_CUSTOMIZATION = 'SET_AIRTABLE_CUSTOMIZATION';

export const TOGGLE_USER_INFO_MODAL = 'TOGGLE_USER_INFO_MODAL';


export const SET_LOT = 'SET_LOT';
export const SET_PLAN = 'SET_PLAN';

export const IS_POPUP = 'IS_POPUP';

export const CUSTOMIZATION = 'CUSTOMIZATION';
export const FLOORPLAN = 'FLOORPLAN';

export const SET_CUSTOMIZATION_PRICE="CUSTOMIZATION_PRICE"

export const CLIENT_REQUEST="CLIENT_REQUEST"
export const CLIENT_SUCCESS="CLIENT_SUCCESS"
export const CLIENT_ERROR="CLIENT_ERROR"

export const MARKUP_REQUEST="MARKUP_REQUEST"
export const MARKUP_SUCCESS="MARKUP_SUCCESS"
export const MARKUP_ERROR="MARKUP_ERROR"

export const FLOORPLAN_REQUEST="FLOORPLAN_REQUEST"
export const FLOORPLAN_SUCCESS="FLOORPLAN_SUCCESS"
export const FLOORPLAN_ERROR="FLOORPLAN_ERROR"


export const FLOORPLAN_FILTER="FLOORPLAN_FILTER"
export const FLOORPLAN_FILTER_CLEAR="FLOORPLAN_FILTER_CLEAR"



export const CONSTRUCTION_COST_REQUEST="CONSTRUCTION_COST_REQUEST"
export const CONSTRUCTION_COST_SUCCESS="CONSTRUCTION_COST_SUCCESS"
export const CONSTRUCTION_COST_ERROR="CONSTRUCTION_COST_ERROR"





