

//27066 
const plans = [
  {
    id: 1,
    img: '/plans/edison-fairmont/img3.webp',
    rums: 6,
    toilet: 3,
    kitchenSize: 12,
    bedrooms: 3,
    bathrooms: 2,
    ceil: 4,
    s: 1200,
    images: ['/plans/edison-fairmont/img2.webp', '/plans/edison-fairmont/img3.webp'],
    price: 73252.00,
    title: "Barton II - MHE",
    manufacturer: "MHE",
    type: "typeA",
  },
  {
    id: 2,
    img: '/plans/davinci-fairmont/img1.webp',
    rums: 9,
    toilet: 5,
    kitchenSize: 5,
    bedrooms: 3,
    bathrooms: 2,
    ceil: 4,
    s: 1500,
    images: ['/plans/davinci-fairmont/img2.webp', '/plans/davinci-fairmont/img1.webp'],
    price: 91656.00,
    title: "Newport - Fairmont",
    manufacturer: "Fairmont",
    type: "typeA",
  },

  {
    id: 3,
    img: '/plans/franklin-fairmont/img1.webp',
    rums: 7,
    toilet: 2,
    kitchenSize: 5,
    bedrooms: 3,
    bathrooms: 2,
    ceil: 2.6,
    s: 1500,
    images: ['/plans/franklin-fairmont/img2.webp', '/plans/franklin-fairmont/img1.webp'],
    price: 84243.00,
    title: "Glenn Forest - MHE",
    manufacturer: "MHE",
    type: "typeA",
  },

  {
    id: 4,
    img: '/plans/glenn-creek-mhe/img1.webp',
    rums: 2,
    toilet: 2,
    kitchenSize: 8,
    bedrooms: 2,
    bathrooms: 2,
    ceil: 2.8,
    s: 1200,
    images: ['/plans/glenn-creek-mhe/img2.webp', '/plans/glenn-creek-mhe/img1.webp'],
    price: 72887.00,
    title: "Woodland Bay - Fairmont",
    manufacturer: "Fairmont",
    type: "typeA",
  },
  {
    id: 5,
    img: '/plans/dyson-fairmont/img3.webp',
    rums: 5,
    toilet: 5,
    kitchenSize: 7,
    bedrooms: 3,
    bathrooms: 2,
    ceil: 3,
    s: 1200,
    images: ['/plans/dyson-fairmont/img2.webp', '/plans/dyson-fairmont/img3.webp'],
    price: 73252.00,
    title: "Barton - MHE",
    manufacturer: "MHE",
    type: "typeA",
  },
  {
    id: 6,
    img: '/plans/barton-mhe/img1.webp',
    rums: 4,
    toilet: 1,
    kitchenSize: 9,
    bedrooms: 3,
    bathrooms: 2,
    ceil: 2.4,
    s: 2000,
    images: [`/plans/barton-mhe/img2.webp`, '/plans/barton-mhe/img1.webp'],
    price: 105897.00,
    title: "Redbud - MHE",
    manufacturer: "MHE",
    type: "typeA",
  },
  {
    id: 7,
    img: '/plans/barton2-mhe/img1.webp',
    rums: 5,
    toilet: 1,
    kitchenSize: 9,
    bedrooms: 4,
    bathrooms: 2,
    ceil: 2.4,
    s: 2000,
    images: ['/plans/barton2-mhe/img2.webp', '/plans/barton2-mhe/img1.webp'],
    price: 131443.00,
    title: "Goldberg - Fairmont",
    manufacturer: "Fairmont",
    type: "typeA",
  },
  // {
  //   id: 9,
  //   img: '/plans/leonardo-fairmont/img3.webp',
  //   rums: 7,
  //   toilet: 1,
  //   kitchenSize: 4,
  //   bedrooms: 4,
  //   bathrooms: 2,
  //   ceil: 3,
  //   s: 1500,
  //   images: ['/plans/leonardo-fairmont/img2.webp', '/plans/leonardo-fairmont/img3.webp'],
  //   price: 105946.1,
  //   title: "Leonardo - Fairmont",
  //   manufacturer: "Fairmont",
  //   type: "typeA",
  // },
  // {
  //   id: 4,
  //   img: '/plans/hazlenut-mhe/img2.webp',
  //   rums: 8,
  //   toilet: 4,
  //   kitchenSize: 3,
  //   bedrooms: 4,
  //   bathrooms: 2,
  //   ceil: 2.6,
  //   s: 1600,
  //   images: ['/plans/hazlenut-mhe/img2.webp'],
  //   price: 104802.1,
  //   title: "Hazlenut -  MHE",
  //   manufacturer: "MHE",
  //   type: "typeA",
  // },
];

export default plans;